# Generated by Django 4.1 on 2022-10-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormeMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme_med', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_soins', models.CharField(max_length=150, null=True)),
                ('medecin', models.CharField(max_length=150, null=True)),
                ('patient', models.CharField(max_length=150, null=True)),
                ('freq_med', models.CharField(max_length=150, null=True)),
                ('prise_min', models.FloatField()),
                ('prise_max', models.FloatField()),
                ('forme_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convertion.formemed')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convertion.medicament')),
                ('qte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convertion.quantite')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convertion.unite')),
            ],
        ),
    ]
